[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection=false

[theme]
base="dark"

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = false

[ui]
hideTopBar = true

[logger]
level = "error"

